language: shell

os:
  - linux
  - osx

env:
  - SH=bash
  - SH=dash
  - SH=ksh

addons:
  apt:
    packages:
      - bash
      - dash
      - ksh
  homebrew:
    packages:
      - bash
      - dash
      - ksh

install:
  # add tag to simulate release
  - echo 'version.sh export-subst' > .gitattributes
  - git add .gitattributes
  - git commit -m Travis
  - git tag -a $TRAVIS_JOB_ID -m Travis

script:
  - set +x
  # check that commands in git repository return expected results
  - $SH -c 'echo running in $0'
  - $SH ./version.sh json
  - test $($SH ./version.sh version) == $TRAVIS_JOB_ID
  - test $($SH ./version.sh commit) == $(git rev-parse HEAD)
  # work from a source tarball and check that it produces identical output
  - cd $(mktemp -d)
  - git -C $TRAVIS_BUILD_DIR archive HEAD | tar xv
  - $SH ./version.sh json
  - test "$($SH ./version.sh json)" == "$(cd $TRAVIS_BUILD_DIR && $SH ./version.sh json)"
  # back to repository and add a commit
  - cd $TRAVIS_BUILD_DIR
  - git commit --allow-empty -m 'edit'
  - test $($SH ./version.sh describe) == $(git describe)
